# Generated by Django 5.2.11 on 2026-09-10 07:30

from datetime import date

from django.db import migrations, models


def populate_receipt_numbers(apps, schema_editor):
    FeePayment = apps.get_model('payments', 'FeePayment')
    year = date.today().year
    prefix = f'FF-{year}-'
    taken = set(FeePayment.objects.exclude(receipt_number='').exclude(receipt_number__isnull=True).values_list('receipt_number', flat=True))
    counter = 1
    for payment in FeePayment.objects.order_by('id'):
        if payment.receipt_number:
            continue
        while True:
            candidate = f'{prefix}{counter:06d}'
            if candidate not in taken:
                payment.receipt_number = candidate
                taken.add(candidate)
                payment.save(update_fields=['receipt_number'])
                counter += 1
                break
            counter += 1


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(blank=True, default='Cash', max_length=50),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='receipt_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.RunPython(populate_receipt_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='feepayment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, unique=True),
        ),
    ]
