# Generated by Django 5.2.11 on 2026-09-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_feepayment_payment_method_feepayment_receipt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
