# Generated by Django 5.2.6 on 2026-09-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_notification"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="feepayment",
            constraint=models.UniqueConstraint(
                condition=~models.Q(transaction_id=""),
                fields=("transaction_id",),
                name="unique_nonblank_payment_transaction_id",
            ),
        ),
    ]