# Generated by Django 5.2.17 on 2026-09-10 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=10),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILURE', 'Login failure'), ('LOGOUT', 'Logout'), ('STUDENT_CREATED', 'Student created'), ('STUDENT_UPDATED', 'Student updated'), ('CREDENTIALS_RESENT', 'Credentials resent'), ('PAYMENT_CREATED', 'Payment created'), ('REMINDER_SENT', 'Reminder sent'), ('NOTIFICATION_RETRIED', 'Notification retried'), ('TEACHER_CREATED', 'Teacher created'), ('TEACHER_UPDATED', 'Teacher updated'), ('TEACHER_STATUS_CHANGED', 'Teacher status changed'), ('PASSWORD_CHANGED', 'Password changed')], db_index=True, max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target_type', models.CharField(blank=True, default='', max_length=80)),
                ('target_id', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp', '-pk'),
                'indexes': [models.Index(fields=['user', '-timestamp'], name='users_audit_user_id_29b33e_idx'), models.Index(fields=['action', '-timestamp'], name='users_audit_action_e79129_idx')],
            },
        ),
    ]
