# Generated by Django 5.2.17 on 2026-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILURE', 'Login failure'), ('LOGOUT', 'Logout'), ('STUDENT_CREATED', 'Student created'), ('STUDENT_UPDATED', 'Student updated'), ('STUDENT_STATUS_CHANGED', 'Student status changed'), ('CREDENTIALS_RESENT', 'Credentials resent'), ('PAYMENT_CREATED', 'Payment created'), ('REMINDER_SENT', 'Reminder sent'), ('NOTIFICATION_RETRIED', 'Notification retried'), ('TEACHER_CREATED', 'Teacher created'), ('TEACHER_UPDATED', 'Teacher updated'), ('TEACHER_STATUS_CHANGED', 'Teacher status changed'), ('PASSWORD_CHANGED', 'Password changed')], db_index=True, max_length=40),
        ),
    ]
